## 분석용 기초 이론

### 리스트 컴프리헨션
- 기존의 리스트 사용법을 좀 더 간결하고 효율적으로 사용위해서

In [ ]:
# 기존방식 1
result1 = []
for i in range(10):
    result1.append(i)

In [2]:
result1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# 기존방식 2
result1.clear()

for i in range(2,40,2):
    result1.append(i)

In [8]:
result1

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]

In [9]:
# 리스트 컴프리헨선 방식 1
result2 = [i for i in range(10)]

In [10]:
result2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
# 리스트 컴프리헨션 방식 2
result2 = [i for i in range(2,40,2)]

In [12]:
result2

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]

In [15]:
result2 = [i*2 for i in range(1,20)]
result2

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]

In [17]:
result2 = [i for i in range(1,40) if i % 2 ==0]
result2

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]

In [16]:
coord = [(x,y) for x in range(3) for y in range(3)]
coord

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]

- 코드 줄 수 감소, 가독성 좋음, 속도도 조금 빠름

## 파일입출력

In [18]:
import csv

In [ ]:
with open('./부산시_해운대구_도서정보.csv','r', encoding = 'utf-8') as f:
    reader = csv.reader(f)
    for row in reader:
        print(row)

### NumPy
- 행렬이나 대규모 차원의 배열을 쉽게 처리하도록 지원하는 파이썬 수치 라이브러리
- 수치해석용 핵심 엔진
- SciPy, SymPy 관련 라이브러리
- Matplotlib, Pandas, PyTorch 등과 상호연동

#### 설치
- 일반 콘솔 설치
```bash
pip install numpy
```

- 주피터 노트북에서 설치
``` python
!pip install numpy
```

In [20]:
!pip install numpy


[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


#### Python 리스트와 NumPy 배열의 차이

- Python 리스트는 한 요소끼리 더하는 작업을 반복문 사용해서 처리

In [ ]:
# Python 리스트
a = [1,2,3]
b = [4,5,6]

res_list = [a[i] + b[i] for i in range(3)]  # 리스트 컴프리헨션
res_list

[5, 7, 9]

In [ ]:
res_list = []

for i in range(3): # 일반 반복문
    res_list.append(a[i]+b[i])

res_list

[5, 7, 9]

In [26]:
# NumPy 소스코드에 포함
import numpy as np # 줄여서 np로 사용

- Numpy 배열은 배열로 형변환하면 + 연산으로 처리가 가능

In [27]:
# NumPy 배열
na = np.array(a)
na

array([1, 2, 3])

In [28]:
nb = np.array(b)

na + nb

array([5, 7, 9])

In [ ]:
# 배열 생성
np.zeros(5) # 1차원 배열 0 초기화

array([0., 0., 0., 0., 0.])

In [38]:
# Python 리스트 비교
# 안쓰는 변수는 i 대신 _로 변경해도 무방
[0 for _ in range(5)]

[0, 0, 0, 0, 0]

In [33]:
np.zeros((4,5)) # 4행 5열 2차원 배열

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# Python 기본 2차원 리스트 만들기
[[0 for _ in range(5)] for _ in range(4)]

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]

In [34]:
np.ones(4)

array([1., 1., 1., 1.])

In [35]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
# [0 ~ 9] 리스트
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [41]:
np.arange(10,0,-2)

array([10,  8,  6,  4,  2])

In [50]:
np.arange(8,-1,-2)

array([8, 6, 4, 2, 0])

In [ ]:
# 0부터 1까지 5등분
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [46]:
# 브로드캐스팅
c = np.array([1,3,5,7,9])

c + 10

array([11, 13, 15, 17, 19])

In [ ]:
# 비교연산 한꺼번에 수행
d = np.array([10,20,30,40,50])

d>25

array([False, False,  True,  True,  True])

In [ ]:
# 데이터분석 할 때 중요!
d[d > 25]

array([30, 40, 50])

In [56]:
[i for i in range(10) if i % 2==0]

[0, 2, 4, 6, 8]

In [57]:
np.where(np.arange(10) % 2 == 0) 

(array([0, 2, 4, 6, 8]),)